version: '3'

services:
  postgres:
    image: postgres:15
    container_name: mem0-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mem0
    ports:
      - "5433:5432"  # Use 5433 to avoid conflict with the main database
    volumes:
      - mem0-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  mem0:
    image: mem0ai/mem0:latest
    container_name: mem0-server
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/mem0
    ports:
      - "8050:8050"
    restart: unless-stopped

volumes:
  mem0-postgres-data: